/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_commonsware_abj_interp_lua_LuaInterpreter */

#ifndef _Included_com_commonsware_abj_interp_lua_LuaInterpreter
#define _Included_com_commonsware_abj_interp_lua_LuaInterpreter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_commonsware_abj_interp_lua_LuaInterpreter
 * Method:    executeLua
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_commonsware_abj_interp_lua_LuaInterpreter_executeLua
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
